### ISSUE TITLE
git分支管理：创建与合并分支

### ISSUE THREAD

**Issue by xiaoqinqiu** [wittyResry/myIssue#52]
- 首先，我们创建dev分支，然后切换到dev分支：
$ git checkout -b dev
Switched to a new branch 'dev'
git checkout命令加上-b参数表示创建并切换，相当于以下两条命令：
$ git branch dev
$ git checkout dev
Switched to branch 'dev'

- 用git branch命令查看当前分支：
$ git branch
/* dev
  master
git branch命令会列出所有分支，当前分支前面会标一个*号。

- 在dev分支上正常提交
$ git add testcases/consensus_cases/4nodes/test_1down_after_1restart_2down.py
$ git commit -m testcases/consensus_cases/4nodes/test_1down_after_1restart_2down.py
[qiuxiaoqin eaffba0] testcases/consensus_cases/4nodes/test_1down_after_1restart_2down.py
 1 file changed, 9 insertions(+), 6 deletions(-)

- 从远程库中获取某个分支的更新，再与本地指定的分支进行自动merge。
$ git pull origin release1.4:qiuxiaoqin
若要与本地当前分支merge，则冒号后面的<本地分支名>可以不写。
若本地develop分支与远程的develop分支有追踪关系 ，则直接git pull就行

- 合并指定分支到当前分支
$ git merge dev
Updating 90bc1f7..45ae9a9
Fast-forward
 readme.txt | 1 +
 1 file changed, 1 insertion(+)

- 合并完成后，删除分支：
$ git branch -d dev
Deleted branch dev (was 45ae9a9).

- 推送本地分支local_branch到远程分支remote_branch并建立关联关系
1.远程已有remote_branch分支并且已经关联本地分支local_branch且本地已经切换到local_branch
git push
2.远程已有remote_branch分支但未关联本地分支local_branch且本地已经切换到local_branch
git push -u origin/remote_branch
3.远程没有remote_branch分支并且本地已经切换到local_branch
git push origin local_branch:remote_branch

- 重命名分支
git branch -m | -M oldbranch newbranch 重命名分支，如果newbranch名字分支已经存在，则需要使用-M强制重命名，否则，使用-m进行重命名。

- 删除分支
git branch -d | -D branchname 删除branchname分支
git branch -d -r branchname 删除远程branchname分支

**Comment by xiaoqinqiu** [comment]
**## hypersonic提交操作步骤：**
1.  git pull 将本地分支的代码与远程最新分支保持一致
2.  git diff .py 查看不同的地方是否是修改之处
3. git status
4. git add 需提交的文件
5. git status 查看add 的是否是需要push的文件
5. git commit -m “   备注”
6. git push

**Comment by wittyResry** [comment]
git log -p memcached.h
